services:
  python-app:
    container_name: python-app
    #restart: unless-stopped
    #tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      - FLASK_APP=flask_app
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8080
    ports:
      - "8080:8080"
